[package]
name = "rest-chat"
version = "0.1.0"
authors = ["evgenius2020 <spleen47@mail.ru>"]

[dependencies]
serde = "1.0"
serde_json = "1.0.32"
serde_derive="1.0"
uuid = {version="0.7", features = ["v4"]}
ws = "0.7.9"
env_logger = "0.6.0"