[package]
name = "chat_tree"
version = "0.1.0"
authors = ["evgenius2020 <spleen47@mail.ru>"]

[dependencies]
rand = "0.5.0"
uuid = { version = "0.7", features = ["v4"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"