[package]
name = "rest-chat"
version = "0.1.0"
authors = ["evgenius2020 <spleen47@mail.ru>"]

[dependencies]
hyper = "0.12.14"
pretty_env_logger = "0.2.5"
futures = "0.1.25"
serde = "1.0"
serde_json = "1.0.32"
serde_derive="1.0"
uuid = {version="0.7", features = ["v4"]}
url = "1.7.2"
